"""Pluggable LLM client interface for the agent loop.

The harness never imports a specific provider. Agents receive an
``AgentClient`` that exposes a single ``complete(prompt) -> str`` coroutine-like
method. Real providers (OpenAI, Anthropic, local vLLM, ...) register themselves
via :func:`register_client`; the CLI selects one with ``--agent``.
"""

from __future__ import annotations

from typing import Callable, Dict, Protocol, runtime_checkable


@runtime_checkable
class AgentClient(Protocol):
    """Minimal contract every model backend must satisfy."""

    name: str

    def complete(self, prompt: str, **kwargs) -> str:
        """Return the model's completion text for ``prompt``."""
        ...


class DummyClient:
    """Deterministic offline client used by the scaffold / tests.

    It does not call any network. It echoes a fixed template so the agent loop
    and harness can be exercised end-to-end without credentials.
    """

    name = "dummy"

    def complete(self, prompt: str, **kwargs) -> str:
        # The stub agent turns this into a placeholder PoC; see agent.py.
        return (
            "# STUB PoC generated by DummyClient\n"
            "# Replace with a real proof-of-concept that triggers the vuln.\n"
            "import sys\n"
            "sys.stdout.buffer.write(b'\\x41' * 1024)\n"
        )


# Registry of client factories: name -> callable([kwargs]) -> AgentClient
_REGISTRY: Dict[str, Callable[..., AgentClient]] = {
    "dummy": lambda **k: DummyClient(),
}


def register_client(name: str, factory: Callable[..., AgentClient]) -> None:
    """Register a new backend factory under ``name``."""
    _REGISTRY[name] = factory


def get_client(name: str, **kwargs) -> AgentClient:
    """Construct a client by registered name.

    Unknown names fall back to ``dummy`` (the only client shipped in the
    scaffold) and emit a warning, so the CLI stays runnable out of the box.
    """
    if name not in _REGISTRY:
        import warnings

        warnings.warn(
            f"Unknown client {name!r}; falling back to 'dummy'. "
            "Register a provider with register_client()."
        )
        name = "dummy"
    return _REGISTRY[name](**kwargs)


# --------------------------------------------------------------------------- #
# Example: how a real provider would register itself (left commented so the
# scaffold has no hard dependency on any SDK).
#
# def _make_openai(model="gpt-4o", api_key=None, **_):
#     from openai import OpenAI
#     client = OpenAI(api_key=api_key)
#     class _OpenAIClient:
#         name = "openai"
#         def complete(self, prompt, **kw):
#             r = client.chat.completions.create(
#                 model=model, messages=[{"role": "user", "content": prompt}],
#                 **kw)
#             return r.choices[0].message.content
#     return _OpenAIClient()
#
# register_client("openai", _make_openai)
# --------------------------------------------------------------------------- #
